### ISSUE TITLE
cmake deprecation warning

### ISSUE THREAD

**Issue by willie** [jbaldwin/libcappuccino#25]
I've just started using your library (thank you for it), but I thought I would pass along a warning that cmake is giving me now. I think its weird on the part of cmake, but, nevertheless.

```
CMake Deprecation Warning at build/_deps/cappuccino-src/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```

**Comment by willie** [comment]
I should note that if someone else comes along and this project hasn't been updated (I'd file a PR, but I don't know the author's wishes) and they want the warning gone, you can put this line (as a workaround) in front of your `FetchContent_Declare`:
```
SET(CMAKE_WARN_DEPRECATED OFF CACHE BOOL "CAPPUCCINO_BUILD_TESTS" FORCE)
```

**Comment by jbaldwin** [comment]
Hey, thanks for opening an issue and glad you're liking the library.  Would you be willing to open a PR to fix the warning?

**Comment by willie** [comment]
Sure, I'll do that.

**Comment by willie** [comment]
Pull request filed #26
