### ISSUE TITLE
Compilation error in gcc-13 due to missing <cstdint> include in allow.hpp

### ISSUE THREAD

**Issue by marcbak** [jbaldwin/libcappuccino#27]
Hello, I've recently came across compilation errors when using gcc-13.
`allow.hpp` does not include` <cstdint>` therefore the uint64_t is not defined, the solution is to simply add `#include <cstdint>` in the file.
It's mentioned here: https://gcc.gnu.org/gcc-13/porting_to.html it's due to some STL libraries not including `cstdint` along the way.
I can file a PR if you want to.

**Comment by jbaldwin** [comment]
Hey thanks for opening an issue. A PR would be awesome!

**Comment by marcbak** [comment]
Sorry, I'm kind of new to participating in public repo's, I can't push my branch for PR due to insufficient permissions I think.
Here's the git diff:
`diff --git a/inc/cappuccino/allow.hpp b/inc/cappuccino/allow.hpp
index 7754367..000f8fa 100644
--- a/inc/cappuccino/allow.hpp
+++ b/inc/cappuccino/allow.hpp
@@ -1,5 +1,6 @@
 #pragma once

+#include <cstdint>
 #include <string>

 namespace cappuccino`

**Comment by jbaldwin** [comment]
If you fork the repo, push a branch to your fork and then open a PR against this repo as the base it should work if you want to give it a try, Google might help here too, there are probably some guides out there.  If not I can probably get to it in a few days on this long weekend 🙂.

**Comment by marcbak** [comment]
@jbaldwin yup, just did that, I'll try to address other PR must haves.

**Comment by jbaldwin** [comment]
Awesome, I've approved the CI run!

**Comment by marcbak** [comment]
Seems like first CI fails with:
`Package 'clang-9' has no installation candidate` which I believe is unrelated to my changes.
The other one is MINSIGSTKSZ not being constexpr due to call to sysconf(int) not being constexpr.

I think both are unrelated to my changes?

**Comment by jbaldwin** [comment]
In this file: https://github.com/jbaldwin/libcappuccino/blob/master/.github/workflows/ci.yml try removing the "-9" from the gcc and clang installations and push to your branch to run CI again.  Let's see if that helps, ideally we'd add CI runs per gcc or clang version but I think we can try latest for now.

**Comment by marcbak** [comment]
Gotcha, however I'll still probably still hit issue when setting ` -DCMAKE_CXX_COMPILER=clang++-9`. 
I'll let it run and update the compiler if I can make out which clang version it installs by default.

**Comment by jbaldwin** [comment]
Oh good catch.  I think you're right that also needs to be changed.

**Comment by marcbak** [comment]
I've set -DCMAKE_CXX_COMPILER=clang++ in my latest commit, hopefully the one that's installed without specifying clang version will also work for this CMake flag?

**Comment by jbaldwin** [comment]
It should... I'm like 99% sure I've done that before.

**Comment by marcbak** [comment]
Sure, let's get clang out of the way first and we can think about gcc next :).

**Comment by marcbak** [comment]
I think CI needs approval to run from you @jbaldwin

**Comment by marcbak** [comment]
Sorry, I was wrong, while clang did work just fine, it still hit the same constexpr/consteval issue I mentioned previously.
I've pushed two commits, one removing constexpr, the other one removing g++ version, defaulting to latest.

**Comment by jbaldwin** [comment]
Cool, I'll keep approving.  It makes me do that since your a first time contributor on this repo, any PRs after this one will automatically run

**Comment by marcbak** [comment]
Okay, so I think I finally found what the problem is, the catch library you're using in tests is outdated, this https://github.com/catchorg/Catch2/blob/devel/docs/release-notes.md#2135 specifically mentions that MINSIGSTKSZ is no longer constexpr.
https://stackoverflow.com/questions/71454588/minsigstksz-error-after-update-in-my-manjaro-linux also metnions that.
I think the best way to go ahead would be to update catch library since it's not used as git submodule.

I've pushed a PR to undefine then define it to some arbitrary size, but that's a temporary solution.

**Comment by jbaldwin** [comment]
Makes sense, perhaps copy in the latest release and let's see how it does?  Good find

**Comment by marcbak** [comment]
I've found amalgamated catch header and just C&P'd it over the current implementation.
Let's see how it works.

**Comment by marcbak** [comment]
Sigh... I've added the actual .cpp definitions and added catch as a CMakeLists target to hopefully avoid linker errors.

**Comment by marcbak** [comment]
So, my latest change does indeed result in CI passing, do you want me to squash commit?

**Comment by jbaldwin** [comment]
Awesome, squashed and committed! Thanks for working through the various issues 😃

**Comment by marcbak** [comment]
No problem, though I still think my catch solution is only temporary, food for thought though :)..
Thanks for the feedback and thanks for approving my PR after all, cheers!

**Comment by marcbak** [comment]
Please do another release though so that you library inclusion can be bumped up as well!

**Comment by jbaldwin** [comment]
Can do, I'm on a phone right now so when I get back to my laptop later this weekend I will. I'll open an issue so I don't forget.

**Comment by jbaldwin** [comment]
https://github.com/jbaldwin/libcappuccino/issues/29

**Comment by jbaldwin** [comment]
Are you good if we close this issue?

**Comment by marcbak** [comment]
Of course, let me close it
